In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import scipy as sp
import matplotlib.pyplot as plt

setting = pd.read_csv('setting.csv', header = 0, usecols = [0,1])
EMG_features = setting.iloc[0,1]
IK = setting.iloc[1,1]
ID = setting.iloc[2,1]
output_name = setting.iloc[4,1]
output_path = setting.iloc[3,1]

In [2]:
df_EMG = pd.read_csv(EMG_features, header=0)
df_EMG.describe()

,Time,DEMG1_AR1,DEMG1_AR2,DEMG1_AR3,DEMG1_AR4,DEMG1_AR5,DEMG1_AR6,DEMG1_RMS,DEMG1_MAV,DEMG2_AR1,...,DEMG13_RMS,DEMG13_MAV,DEMG14_AR1,DEMG14_AR2,DEMG14_AR3,DEMG14_AR4,DEMG14_AR5,DEMG14_AR6,DEMG14_RMS,DEMG14_MAV
count,5828.000000,5828.000000,5828.000000,5828.000000,5828.000000,5828.000000,5828.000000,5828.000000,5828.000000,5828.000000,...,5828.000000,5828.000000,5828.000000,5828.000000,5828.000000,5828.000000,5828.000000,5828.000000,5828.000000,5828.000000
mean,145.675000,0.891512,-0.936979,0.765508,-0.757936,0.460684,-0.333252,0.018782,0.014270,0.773036,...,0.046123,0.032547,0.609864,-0.892743,0.679016,-0.690626,0.311019,-0.345980,0.058566,0.042083
std,84.127151,0.293920,0.261389,0.231371,0.186928,0.147002,0.086264,0.026849,0.020453,0.364196,...,0.033247,0.023193,0.305144,0.227527,0.193747,0.203342,0.162794,0.085715,0.034316,0.024022
min,0.000000,-0.088823,-1.997682,0.107494,-1.586285,0.016857,-0.875331,0.003841,0.002943,-0.194596,...,0.008349,0.006350,-0.162337,-1.722916,0.042614,-1.365021,-0.122430,-0.694323,0.013421,0.010281
25%,72.837500,0.672143,-1.108225,0.600924,-0.879093,0.356315,-0.391060,0.007070,0.005534,0.470578,...,0.014713,0.011533,0.377262,-1.055812,0.545929,-0.834715,0.185455,-0.402569,0.023670,0.018569
50%,145.675000,0.917895,-0.905849,0.737795,-0.750338,0.454108,-0.334339,0.011437,0.008744,0.785210,...,0.040767,0.027347,0.619922,-0.899208,0.656990,-0.710461,0.302467,-0.346739,0.055927,0.039328
75%,218.512500,1.112773,-0.735032,0.905813,-0.618233,0.560713,-0.274202,0.017176,0.012850,1.071188,...,0.067671,0.047216,0.835034,-0.706594,0.790084,-0.529672,0.425612,-0.292272,0.084473,0.059733
max,291.350000,1.742050,-0.313893,1.795815,-0.224324,1.042505,-0.044604,0.273382,0.217179,1.719636,...,0.202054,0.154965,1.516468,-0.287005,1.581511,-0.120894,0.897462,-0.037823,0.211822,0.140158

In [3]:
df_IK = pd.read_csv(IK, header=0, usecols = [10,11,17,18])
df_IK.describe()

       knee_angle_r  ankle_angle_r  knee_angle_l  ankle_angle_l
count   5830.000000    5830.000000   5830.000000    5830.000000
mean     -59.209422      15.557997    -58.810567      17.040299
std       30.364520      10.364744     30.061072       9.575618
min     -144.498984      -8.286598   -144.257640      -3.148500
25%      -87.842911      11.209935    -87.986130      13.432213
50%      -55.508968      14.849394    -54.382766      16.515374
75%      -27.999990      18.378438    -28.319021      19.077130
max      -21.060826      48.802496    -20.323920      51.973411

In [4]:
df_ID = pd.read_csv(ID, header=0, usecols = [16,17,18,19])
df_ID.describe()

,knee_angle_r_moment,knee_angle_l_moment,ankle_angle_r_moment,ankle_angle_l_moment
count,5830.000000,5830.000000,5830.000000,5830.000000
mean,14.463714,10.348496,-18.964068,-25.422044
std,19.935721,20.707490,18.319634,19.256405
min,-16.090159,-25.829521,-74.083846,-84.839649
25%,2.813524,-1.193371,-28.973942,-38.688749
50%,9.141469,4.225992,-14.007884,-22.793936
75%,16.251134,13.334953,-4.107678,-8.895778
max,122.433245,115.806266,6.750808,1.693709

In [5]:
data_frame = pd.concat([df_EMG,df_IK,df_ID],axis = 1)
data_frame.describe()

,Time,DEMG1_AR1,DEMG1_AR2,DEMG1_AR3,DEMG1_AR4,DEMG1_AR5,DEMG1_AR6,DEMG1_RMS,DEMG1_MAV,DEMG2_AR1,...,DEMG14_RMS,DEMG14_MAV,knee_angle_r,ankle_angle_r,knee_angle_l,ankle_angle_l,knee_angle_r_moment,knee_angle_l_moment,ankle_angle_r_moment,ankle_angle_l_moment
count,5828.000000,5828.000000,5828.000000,5828.000000,5828.000000,5828.000000,5828.000000,5828.000000,5828.000000,5828.000000,...,5828.000000,5828.000000,5830.000000,5830.000000,5830.000000,5830.000000,5830.000000,5830.000000,5830.000000,5830.000000
mean,145.675000,0.891512,-0.936979,0.765508,-0.757936,0.460684,-0.333252,0.018782,0.014270,0.773036,...,0.058566,0.042083,-59.209422,15.557997,-58.810567,17.040299,14.463714,10.348496,-18.964068,-25.422044
std,84.127151,0.293920,0.261389,0.231371,0.186928,0.147002,0.086264,0.026849,0.020453,0.364196,...,0.034316,0.024022,30.364520,10.364744,30.061072,9.575618,19.935721,20.707490,18.319634,19.256405
min,0.000000,-0.088823,-1.997682,0.107494,-1.586285,0.016857,-0.875331,0.003841,0.002943,-0.194596,...,0.013421,0.010281,-144.498984,-8.286598,-144.257640,-3.148500,-16.090159,-25.829521,-74.083846,-84.839649
25%,72.837500,0.672143,-1.108225,0.600924,-0.879093,0.356315,-0.391060,0.007070,0.005534,0.470578,...,0.023670,0.018569,-87.842911,11.209935,-87.986130,13.432213,2.813524,-1.193371,-28.973942,-38.688749
50%,145.675000,0.917895,-0.905849,0.737795,-0.750338,0.454108,-0.334339,0.011437,0.008744,0.785210,...,0.055927,0.039328,-55.508968,14.849394,-54.382766,16.515374,9.141469,4.225992,-14.007884,-22.793936
75%,218.512500,1.112773,-0.735032,0.905813,-0.618233,0.560713,-0.274202,0.017176,0.012850,1.071188,...,0.084473,0.059733,-27.999990,18.378438,-28.319021,19.077130,16.251134,13.334953,-4.107678,-8.895778
max,291.350000,1.742050,-0.313893,1.795815,-0.224324,1.042505,-0.044604,0.273382,0.217179,1.719636,...,0.211822,0.140158,-21.060826,48.802496,-20.323920,51.973411,122.433245,115.806266,6.750808,1.693709

In [6]:
output_file = output_path + output_name + '.csv'
data_frame.to_csv(output_file, index = False)